// 4.webpack-react/src/components/App.jsx
import data from '@public/data.json'
import {useState} from "react";

export default function App(){
    console.log(data)
    const [count, setCount] = useState(0);

    return <div>
        <h1>피카츄12</h1>
        <div>{count}</div>
        <button onClick={()=> setCount(prev=> prev+1)}>UPUP</button>
        <img src='/pica.png' alt=""/>
    </div>
}

// 5-3.webpack-vue-final/src/components/App.vue
<template>
  <div>
    <h1>App Component 2</h1>
    <h2>count: {{count}}</h2>
    <button @click="count++">+</button>
    <img :src="ImgSrc" alt="">
    <div>{{data}}</div>
  </div>
</template>

<script lang="ts">
import ImgSrc from '@public/pica.png';
import data from '@public/data.json';
import Vue from "vue";

export default Vue.extend({
  data() {
    return {
      count: 0,
      ImgSrc,
      data
    }
  }
})
</script>

<style>
 h1 {
  color: red;
}
</style>
